// Application configuration for Bafang 1000W Hub Motor
// Optimized for e-bike throttle/pedal assist operation

#ifndef APPCONF_BAFANG_500W_HUB_H_
#define APPCONF_BAFANG_500W_HUB_H_

// VESC ID
#define APPCONF_CONTROLLER_ID 0

// Timeout
#define APPCONF_TIMEOUT_MSEC 1000

// Timeout Brake Current
#define APPCONF_TIMEOUT_BRAKE_CURRENT 0

// CAN Status Message Mode
#define APPCONF_SEND_CAN_STATUS 0

// CAN Status Rate
#define APPCONF_SEND_CAN_STATUS_RATE_HZ 50

// CAN Baud Rate
#define APPCONF_CAN_BAUD_RATE 1

// Pairing Done
#define APPCONF_PAIRING_DONE 0

// Enable Permanent UART
#define APPCONF_PERMANENT_UART_ENABLED 1

// Shutdown Mode
#define APPCONF_SHUTDOWN_MODE 0

// CAN Mode
#define APPCONF_CAN_MODE 0

// UAVCAN ESC Index
#define APPCONF_UAVCAN_ESC_INDEX 0

// UAVCAN Raw Throttle Mode
#define APPCONF_UAVCAN_RAW_MODE 0

// Enable Servo Output
#define APPCONF_SERVO_OUT_ENABLE 0

// APP to Use - ADC for throttle control
#define APPCONF_APP_TO_USE 1

// ADC Configuration for throttle
// Control Type - Current control for smooth operation
#define APPCONF_ADC_CTRL_TYPE 1

// Use filter
#define APPCONF_ADC_USE_FILTER 1

// Safe start
#define APPCONF_ADC_SAFE_START 1

// Button Mode
#define APPCONF_ADC_CC_BUTTON_INVERTED 0

// Voltage start (V)
#define APPCONF_ADC_VOLTAGE_START 0.9

// Voltage end (V) 
#define APPCONF_ADC_VOLTAGE_END 3.0

// Voltage center (V)
#define APPCONF_ADC_VOLTAGE_CENTER 2.0

// Voltage inverted
#define APPCONF_ADC_VOLTAGE_INVERTED 0

// Button voltage start (V)
#define APPCONF_ADC_VOLTAGE2_START 0.9

// Button voltage end (V)
#define APPCONF_ADC_VOLTAGE2_END 3.0

// Button voltage inverted
#define APPCONF_ADC_VOLTAGE2_INVERTED 0

// Throttle curve exponential factor
#define APPCONF_ADC_THROTTLE_EXP 0.0

// Throttle curve exponential factor at brake
#define APPCONF_ADC_THROTTLE_EXP_BRAKE 0.0

// Throttle curve exponential mode
#define APPCONF_ADC_THROTTLE_EXP_MODE 0

// Positive ramping time (ms)
#define APPCONF_ADC_RAMP_TIME_POS 300

// Negative ramping time (ms)  
#define APPCONF_ADC_RAMP_TIME_NEG 200

// Multiple VESCs over CAN
#define APPCONF_ADC_MULTI_ESC 0

// Traction Control
#define APPCONF_ADC_TC 0

// TC Max ERPM Difference
#define APPCONF_ADC_TC_MAX_DIFF 3000

// Max ERPM for direction switch
#define APPCONF_ADC_MAX_ERPM_FOR_DIR 4000

// Current at minimum throttle
#define APPCONF_ADC_CC_CURR_MIN 0

// Current at maximum throttle - Doubled for 1000W
#define APPCONF_ADC_CC_CURR_MAX 70

// PPM Configuration (alternative input method)
// Control Type
#define APPCONF_PPM_CTRL_TYPE 0

// PID Max ERPM
#define APPCONF_PPM_PID_MAX_ERPM 15000

// Input Deadband
#define APPCONF_PPM_HYST 0.15

// Pulselength Start
#define APPCONF_PPM_PULSE_START 1.0

// Pulselength End
#define APPCONF_PPM_PULSE_END 2.0

// Pulselength Center
#define APPCONF_PPM_PULSE_CENTER 1.5

// Median Filter
#define APPCONF_PPM_MEDIAN_FILTER 1

// Safe Start
#define APPCONF_PPM_SAFE_START 1

// Throttle Expo
#define APPCONF_PPM_THROTTLE_EXP 0

// Throttle Expo Brake
#define APPCONF_PPM_THROTTLE_EXP_BRAKE 0

// Throttle Expo Mode
#define APPCONF_PPM_THROTTLE_EXP_MODE 0

// Positive Ramping Time
#define APPCONF_PPM_RAMP_TIME_POS 0.3

// Negative Ramping Time
#define APPCONF_PPM_RAMP_TIME_NEG 0.2

// Multiple VESCs Over CAN
#define APPCONF_PPM_MULTI_ESC 0

// Traction Control
#define APPCONF_PPM_TC 0

// TC Max ERPM Difference
#define APPCONF_PPM_TC_MAX_DIFF 3000

// Max ERPM for direction switch
#define APPCONF_PPM_MAX_ERPM_FOR_DIR 4000

// Smart Reverse Max Duty Cycle
#define APPCONF_PPM_SMART_REV_MAX_DUTY 0.07

// UART App Configuration
#define APPCONF_UART_BAUDRATE 115200

// NunchukApp Configuration
#define APPCONF_CHUK_CTRL_TYPE 0
#define APPCONF_CHUK_HYST 0.15
#define APPCONF_CHUK_RPM_LIM_START 150000
#define APPCONF_CHUK_RPM_LIM_END 200000
#define APPCONF_CHUK_RAMP_TIME_POS 0.4
#define APPCONF_CHUK_RAMP_TIME_NEG 0.2
#define APPCONF_CHUK_STICK_ERPM_PER_S_IN_CC 3000
#define APPCONF_CHUK_MULTI_ESC 0
#define APPCONF_CHUK_TC 0
#define APPCONF_CHUK_TC_MAX_DIFF 3000
#define APPCONF_CHUK_USE_SMART_REV 1
#define APPCONF_CHUK_SMART_REV_MAX_DUTY 0.07
#define APPCONF_CHUK_SMART_REV_RAMP_TIME 3.0

// NRF App Configuration
#define APPCONF_NRF_SPEED 0
#define APPCONF_NRF_POWER 0
#define APPCONF_NRF_CRC 1
#define APPCONF_NRF_RETR_DELAY 0
#define APPCONF_NRF_RETRIES 3
#define APPCONF_NRF_CHANNEL 76
#define APPCONF_NRF_ADDR_0 0xC2C2C2C2C2
#define APPCONF_NRF_ADDR_1 0xC2C2C2C2C3
#define APPCONF_NRF_ADDR_2 0xC2C2C2C2C4
#define APPCONF_NRF_SEND_CRC_ACK 1

// Balance App Configuration (not typically used for hub motors)
#define APPCONF_BALANCE_KP 0.0
#define APPCONF_BALANCE_KI 0.0
#define APPCONF_BALANCE_KD 0.0
#define APPCONF_BALANCE_HERTZ 1000.0
#define APPCONF_BALANCE_LOOP_TIME_FILTER 0.0
#define APPCONF_BALANCE_FAULT_PITCH 20.0
#define APPCONF_BALANCE_FAULT_ROLL 45.0
#define APPCONF_BALANCE_FAULT_DUTY 0.03
#define APPCONF_BALANCE_FAULT_ADC1 0.27
#define APPCONF_BALANCE_FAULT_ADC2 0.27
#define APPCONF_BALANCE_FAULT_DELAY_PITCH 0
#define APPCONF_BALANCE_FAULT_DELAY_ROLL 0
#define APPCONF_BALANCE_FAULT_DELAY_DUTY 0
#define APPCONF_BALANCE_FAULT_DELAY_SWITCH_HALF 0
#define APPCONF_BALANCE_FAULT_DELAY_SWITCH_FULL 0
#define APPCONF_BALANCE_FAULT_ADC_HALF_ERPM 15000
#define APPCONF_BALANCE_FAULT_IS_DUAL_SWITCH 0
#define APPCONF_BALANCE_TILTBACK_ANGLE 15.0
#define APPCONF_BALANCE_TILTBACK_SPEED 5.0
#define APPCONF_BALANCE_TILTBACK_DUTY 0.8
#define APPCONF_BALANCE_TILTBACK_TOTAL_ERPM 15000
#define APPCONF_BALANCE_TILTBACK_RETURN_SPEED 0.0
#define APPCONF_BALANCE_SETPOINT_PITCH_FILTER 0.0
#define APPCONF_BALANCE_SETPOINT_TARGET_FILTER 0.0
#define APPCONF_BALANCE_SETPOINT_FILTER_CLAMP 1.0
#define APPCONF_BALANCE_ATR_RESPONSE_BOOST 0.0
#define APPCONF_BALANCE_ATR_TRANSITION_BOOST 0.0
#define APPCONF_BALANCE_ATR_FILTER 1.0
#define APPCONF_BALANCE_ATR_ANGLE_LIMIT 10.0
#define APPCONF_BALANCE_ATR_ON_SPEED 3.0
#define APPCONF_BALANCE_ATR_OFF_SPEED 1.5
#define APPCONF_BALANCE_ATR_SPEED_BOOST 0.0
#define APPCONF_BALANCE_TURNTILT_STRENGTH 0.0
#define APPCONF_BALANCE_TURNTILT_ANGLE_LIMIT 8.0
#define APPCONF_BALANCE_TURNTILT_START_ANGLE 1.5
#define APPCONF_BALANCE_TURNTILT_START_ERPM 1000
#define APPCONF_BALANCE_TURNTILT_SPEED 5.0
#define APPCONF_BALANCE_TURNTILT_ERPM_BOOST 0.0
#define APPCONF_BALANCE_TURNTILT_ERPM_BOOST_END 20000
#define APPCONF_BALANCE_MAHONY_KP 0.3
#define APPCONF_BALANCE_MAHONY_KI 0.0
#define APPCONF_BALANCE_BOOSTER_ANGLE 8.0
#define APPCONF_BALANCE_BOOSTER_RAMP 1.0
#define APPCONF_BALANCE_BOOSTER_CURRENT 7.0
#define APPCONF_BALANCE_TORQUETILT_START_CURRENT 10.0
#define APPCONF_BALANCE_TORQUETILT_ANGLE_LIMIT 8.0
#define APPCONF_BALANCE_TORQUETILT_ON_SPEED 3.0
#define APPCONF_BALANCE_TORQUETILT_OFF_SPEED 1.5
#define APPCONF_BALANCE_TORQUETILT_STRENGTH 0.0
#define APPCONF_BALANCE_TORQUETILT_FILTER 2.0

// IMU Configuration
#define APPCONF_IMU_TYPE 2
#define APPCONF_IMU_AHRS_MODE 0
#define APPCONF_IMU_SAMPLE_RATE_HZ 200
#define APPCONF_IMU_ACCEL_CONFIDENCE_DECAY 1.0
#define APPCONF_IMU_MAHONY_KP 0.3
#define APPCONF_IMU_MAHONY_KI 0.0
#define APPCONF_IMU_MADGWICK_BETA 0.1
#define APPCONF_IMU_ROT_ROLL 0.0
#define APPCONF_IMU_ROT_PITCH 0.0
#define APPCONF_IMU_ROT_YAW 0.0
#define APPCONF_IMU_ACCEL_OFFSETS {0.0, 0.0, 0.0}
#define APPCONF_IMU_GYRO_OFFSETS {0.0, 0.0, 0.0}

#endif /* APPCONF_BAFANG_500W_HUB_H_ */